version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data  

  frontend:
    build: ./ecom-frontend
    ports:
      - "3000:3000"

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "9090:8080"     # Jenkins UI
      - "50000:50000"   # Jenkins agent
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
